### ISSUE TITLE
Current version not available on Galaxy

### ISSUE THREAD

**Issue by flozzone** [operator-framework/operator-sdk-ansible-util#14]
It looks like the version on Galaxy https://galaxy.ansible.com/operator_sdk/util is older than the version available on this repositories `master` branch.

When do you plan to publish the recent changes on Galaxy?

**Comment by Nicolas-Duboc-IBM** [comment]
The current version on Galaxy is 0.1.0 which doesn't work with Ansible 2.10 and community.kubernetes 1.1.1.

**Comment by fabianvf** [comment]
The updates were published ~6 months ago with 0.2.0, apologies for missing this issue.
