### ISSUE TITLE
Possible to remove value from CR status using operator_sdk.util.k8s_status module?

### ISSUE THREAD

**Issue by lee-cotton** [operator-framework/operator-sdk-ansible-util#23]
I have a situation where we want to completely remove a value from a CR status.
For example I have the following status currently:

```
status:
  version:
     reconciled: 8.0.0
```
Instead of 'version' I need 'versions'. Ie

```
status:
  versions:
     reconciled: 8.0.0
```

I've updated the status on my CR with operator_sdk.util.k8s_status to add 'versions.reconciled'
 so I end up  with:

```
status:
​  version
    ​reconciled: 8.0.0
  versions:
    reconciled: 8.0.0
```

Is there a way I can then use 'operator_sdk.util.k8s_status' to remove this previously added 'version.reconciled status value completely?

**Comment by fabianvf** [comment]
if you set `replace` to True it will send a `PUT` instead of a `PATCH`, which will fully replace the status. Alternatively, if you explicitly null out `version`, the patch request should result in the field being removed ie, your yaml would look like:

```yaml
status:
​  version: null
  versions:
    reconciled: 8.0.0

```
