### ISSUE TITLE
k8s_event hardcode resource API version to v1

### ISSUE THREAD

**Issue by zeusng-fast** [operator-framework/operator-sdk-ansible-util#43]
With k8s_event.py, there is this line:

```
        if involved_obj:
            try:
                involved_object_resource = find_resource(self.client, involved_obj["kind"], "v1")
                api_involved_object = involved_object_resource.get(
                    name=involved_obj["name"], namespace=involved_obj["namespace"])
```
Here, the api_version in find_resource() is hardcoded to v1. We have CRD that use different api_version (e.g. v2, v3). When using k8s_event on such resource, it will split out NULLOBJECT error.

**Comment by everettraven** [comment]
So we should have a parameter than can be configurable, however it is reasonable that we default to using "v1"
