### ISSUE TITLE
k8s_status fails with Ansible 2.10

### ISSUE THREAD

**Issue by willthames** [operator-framework/operator-sdk-ansible-util#5]
With 2.10, we see the behaviour I document in https://github.com/ansible/ansible/issues/70134

Changing the import to 
```
from ansible_collections.community.kubernetes.plugins.module_utils.common import AUTH_ARG_SPEC, COMMON_ARG_SPEC, KubernetesAnsibleModule
```
fixes it for 2.10 but may well break it for older versions.

Just need to decide on a way forward, depending on the outcome of the ansible issue

**Comment by fabianvf** [comment]
I suppose we could always do something like
```
try:
    # old way
except ImportError:
    # new way
```
but ideally it will just be fixed

**Comment by willthames** [comment]
That doesn't work. The import is attempted to be resolved even in a try block

**Comment by Nicolas-Duboc-IBM** [comment]
This issue has been fixed in the current master head (https://github.com/operator-framework/operator-sdk-ansible-util/commit/fe1508dbbab72a6b75dbb9722918cd05f3864d9a).  At least I managed to use the current master with Ansible 2.10.5.

**Comment by robertoayusob** [comment]
I am trying to develop an operator with Ansible and faced this problem.
This are the versions I have:

```
roberto@roberto-Latitude-5580:~$ operator-sdk version
operator-sdk version: "v1.2.0", commit: "215fc50b2d4acc7d92b36828f42d7d1ae212015c", kubernetes version: "v1.18.8", go version: "go1.15.3", GOOS: "linux", GOARCH: "amd64"

roberto@roberto-Latitude-5580:~$ ansible-galaxy collection list -p /home/roberto/.local/lib/python3.8/site-packages
/ansible_collections/  | grep operator
operator_sdk.util 0.1.0  

roberto@roberto-Latitude-5580:~$ ansible --version
ansible 2.10.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/roberto/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/roberto/.local/lib/python3.9/site-packages/ansible
  executable location = /home/roberto/.local/bin/ansible
  python version = 3.9.0+ (default, Oct 20 2020, 08:43:38) [GCC 9.3.0]
```

What do I have to update to have it fixed?

Thanks.
Roberto.

**Comment by Nicolas-Duboc-IBM** [comment]
I installed the module from git with this command : `ansible-galaxy collection install 'git+https://github.com/operator-framework/operator-sdk-ansible-util.git,fe1508dbbab'`

You may have to uninstall the previous version with a `rm -rf` in the local ansible collection directory (e.g. ~/.ansible/collections/ansible_collections/operator_sdk`.

**Comment by everettraven** [comment]
Ansible 2.10 is no longer supported. While the operator-sdk still pins the ansible version to 2.9 we are planning to update our ansible dependency to the latest version (currently 2.14) in the near future. I am closing this issue in anticipation of the ansible bump.

**Comment by asmacdo** [comment]
FWIW 2.10 was never supported. We still support 2.9, and skipped.to 2.11 for preview. 

The reason for this was that 2.10 was sort of halfway in form collections.
